###
// get all posts
GET http://localhost:3000/posts

###
// add a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "sender": "John",
  "title": "My Post",
  "content": "Hello"
}

###
// get posts by sender
GET http://localhost:3000/posts?sender=John

###
// get a specific post by ID
GET http://localhost:3000/posts/69284910476d1b4b94e1d2c6

###
// update a specific post by ID
PUT http://localhost:3000/posts/69284910476d1b4b94e1d2c6
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "Updated content of the post."
}