// posts:
###
// get all posts
GET http://localhost:3000/posts

###
// add a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "sender": "John",
  "title": "My Post",
  "content": "Hello"
}

###
// get posts by sender
GET http://localhost:3000/posts?sender=John

###
// get a specific post by ID
GET http://localhost:3000/posts/692aaf5e94cee70cd74c7a85

###
// update a specific post by ID
PUT http://localhost:3000/posts/692aaf5e94cee70cd74c7a85
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "Updated content of the post."
}


// comments:
###
// add a comment to a specific post
POST http://localhost:3000/comments/692aaf5e94cee70cd74c7a85
Content-Type: application/json

{
  "sender": "Alice",
  "content": "Great post!"
}

###
// delete a specific comment by ID
DELETE http://localhost:3000/comments/692ab18cef0fe489f67e1533

###
// update a specific comment by ID
PUT http://localhost:3000/comments/692aafb494cee70cd74c7a97
Content-Type: application/json

{
  "content": "Updated comment content."
}